name: Gradle CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 设置jdk环境
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: 授予gradlew执行权限
      run: chmod +x gradlew
    - name: 用Gradle构建
      run: ./gradlew build
